### ISSUE TITLE
Automatically require all included adapters

### ISSUE THREAD

**Issue by McPolemic** [searls/fine-ants#6]
Currently, we require adapters individually in [`lib/fine_ants/adapters.rb`][current_requires]. This works out great for a single developer, but as more adapters are created, the odds increase that we'll have merge conflicts due to multiple adapters trying to add requires.

It might be a good idea to automatically require all files in `lib/fine_ants/adapters/` to sidestep this pain.

[current_requires]: https://github.com/searls/fine-ants/blob/efa7025/lib/fine_ants/adapters.rb#L3

**Comment by searls** [comment]
yeah I was going to do this too. Just a quick `Dir['adapters/*.rb'].each { |f| require f }` should do it. Add that and let's cut a release
